//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECPay.SDK.Einvoice.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiUrl_Stage_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiUrl_Stage_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECPay.SDK.Einvoice.Resource.ApiUrl.Stage.Resource", typeof(ApiUrl_Stage_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Invoice/Allowance.
        /// </summary>
        internal static string Allowance {
            get {
                return ResourceManager.GetString("Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Invoice/AllowanceInvalid.
        /// </summary>
        internal static string AllowanceInvalid {
            get {
                return ResourceManager.GetString("AllowanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Query/CheckLoveCode.
        /// </summary>
        internal static string CheckLoveCode {
            get {
                return ResourceManager.GetString("CheckLoveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Query/CheckMobileBarCode.
        /// </summary>
        internal static string CheckMobileBarCode {
            get {
                return ResourceManager.GetString("CheckMobileBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Invoice/Issue.
        /// </summary>
        internal static string InvoiceCreate {
            get {
                return ResourceManager.GetString("InvoiceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Invoice/DelayIssue.
        /// </summary>
        internal static string InvoiceDelay {
            get {
                return ResourceManager.GetString("InvoiceDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Invoice/IssueInvalid.
        /// </summary>
        internal static string InvoiceInvalid {
            get {
                return ResourceManager.GetString("InvoiceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Invoice/TriggerIssue.
        /// </summary>
        internal static string InvoiceTrigger {
            get {
                return ResourceManager.GetString("InvoiceTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Notify/InvoiceNotify.
        /// </summary>
        internal static string Notify {
            get {
                return ResourceManager.GetString("Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Query/Allowance.
        /// </summary>
        internal static string QueryAllowance {
            get {
                return ResourceManager.GetString("QueryAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Query/AllowanceInvalid.
        /// </summary>
        internal static string QueryAllowanceInvalid {
            get {
                return ResourceManager.GetString("QueryAllowanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Query/Issue.
        /// </summary>
        internal static string QueryInvoice {
            get {
                return ResourceManager.GetString("QueryInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://einvoice-stage.ecpay.com.tw/Query/IssueInvalid.
        /// </summary>
        internal static string QueryInvoiceInvalid {
            get {
                return ResourceManager.GetString("QueryInvoiceInvalid", resourceCulture);
            }
        }
    }
}
